# Generated by Django 5.1.4 on 2024-12-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio_imagen_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
